import streamlit as st
from google import genai
from PIL import Image
import io

# --- Web App UI Setup ---
st.set_page_config(page_title="Nano Banana Studio", page_icon="🍌", layout="wide")
st.title("🍌 Nano Banana Studio")
st.markdown("**Created by Sajjad SABOUR**")
st.write("Step 1: Upload a sketch to generate an optimized prompt. Step 2: Edit the prompt and generate the final image.")

st.divider()

# --- Initialize Session State ---
if "generated_prompt" not in st.session_state:
    st.session_state.generated_prompt = ""

# --- Setup the NEW API Client ---
try:
    api_key = st.secrets["API_KEY"]
    # This uses the brand new unified Google GenAI library
    client = genai.Client(api_key=api_key)
except Exception:
    st.error("API Key not found! Please add it to your Streamlit Settings > Secrets.")
    st.stop()

# ==========================================
# STEP 1: ANALYZE IMAGE & WRITE PROMPT
# ==========================================
st.header("1️⃣ Analyze Image & Write Prompt")
col1, col2 = st.columns(2)

with col1:
    uploaded_file = st.file_uploader("Upload your Sketch or Base Image:", type=["jpg", "jpeg", "png"])
with col2:
    target_style = st.selectbox("Target Style:", ["Ultra Realistic Render", "3D Stylized", "Anime / Cel Shaded", "Cinematic Photography", "Cyberpunk"])
    extra_details = st.text_input("Extra Details (Optional):", placeholder="e.g., Make it raining, neon lighting...")

if st.button("Analyze Image & Generate Prompt", type="primary"):
    if not uploaded_file:
        st.warning("Please upload an image first!")
    else:
        with st.spinner("Gemini is analyzing the image structure..."):
            try:
                img = Image.open(uploaded_file)
                
                # Highly strict instructions to prevent camera angle changes
                instruction = f"Act as an expert AI prompt engineer for Nano Banana. Look at the exact structure, composition, and layout of the attached image. {('Additional details: ' + extra_details) if extra_details else ''}. IMPORTANT: The generated prompt MUST strictly enforce keeping the exact same structure, composition, perspective, and camera angle as the uploaded image. Do not change the angle at all. Write a highly detailed, comma-separated prompt to recreate this exact layout as a {target_style} masterpiece. Include lighting and high-quality textures. Only output the raw prompt text."
                
                # New syntax for text generation
                response = client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=[instruction, img]
                )
                
                st.session_state.generated_prompt = response.text.strip()
                st.success("Prompt successfully generated!")
            except Exception as e:
                st.error(f"Error generating prompt: {e}")

st.divider()

# ==========================================
# STEP 2: EDIT PROMPT & GENERATE IMAGE
# ==========================================
st.header("2️⃣ Edit Prompt & Generate Image")

edited_prompt = st.text_area("Review and Edit Your Prompt:", value=st.session_state.generated_prompt, height=150)

if edited_prompt != st.session_state.generated_prompt:
    st.session_state.generated_prompt = edited_prompt

if st.button("Generate Image 🍌", type="primary"):
    if not st.session_state.generated_prompt.strip():
        st.warning("Please generate or write a prompt first!")
    else:
        with st.spinner("Nano Banana is rendering your masterpiece..."):
            try:
                # New syntax for image generation using Nano Banana's backend (imagen-3.0)
                result = client.models.generate_images(
                    model='imagen-3.0-generate-002',
                    prompt=st.session_state.generated_prompt,
                    config=dict(
                        number_of_images=1,
                        aspect_ratio="1:1"
                    )
                )
                
                # The new SDK automatically gives us a clean image object
                final_image = result.generated_images[0].image
                
                st.image(final_image, caption="Generated by Nano Banana Studio", use_container_width=True)
                
                # Convert the image to bytes so the user can download it
                buf = io.BytesIO()
                final_image.save(buf, format="PNG")
                byte_im = buf.getvalue()
                
                st.download_button(
                    label="Download Full Resolution Image 📥",
                    data=byte_im,
                    file_name="nano_banana_render.png",
                    mime="image/png",
                    type="primary"
                )
                
            except Exception as e:
                st.error(f"Image generation failed. Error: {e}")
