import streamlit as st
import google.generativeai as genai
from PIL import Image

# --- Web App UI Setup ---
st.set_page_config(page_title="Nano Banana Studio", page_icon="🍌", layout="wide")
st.title("🍌 Nano Banana Studio")
st.markdown("**Created by Sajjad SABOUR**")
st.write("Step 1: Upload a sketch to generate an optimized prompt. Step 2: Edit the prompt and generate the final image.")

st.divider()

# --- Initialize Session State ---
# This keeps the prompt in memory so it doesn't disappear when you click buttons
if "generated_prompt" not in st.session_state:
    st.session_state.generated_prompt = ""

# --- Setup API Key ---
try:
    api_key = st.secrets["API_KEY"]
    genai.configure(api_key=api_key)
except Exception:
    st.error("API Key not found! Please add it to your Streamlit Settings > Secrets.")
    st.stop()

# ==========================================
# STEP 1: ANALYZE IMAGE & WRITE PROMPT
# ==========================================
st.header("1️⃣ Analyze Image & Write Prompt")
col1, col2 = st.columns(2)

with col1:
    uploaded_file = st.file_uploader("Upload your Sketch or Base Image:", type=["jpg", "jpeg", "png"])
with col2:
    target_style = st.selectbox("Target Style:", ["Ultra Realistic Render", "3D Stylized", "Anime / Cel Shaded", "Cinematic Photography", "Cyberpunk"])
    extra_details = st.text_input("Extra Details (Optional):", placeholder="e.g., Make it raining, neon lighting...")

if st.button("Analyze Image & Generate Prompt", type="primary"):
    if not uploaded_file:
        st.warning("Please upload an image first!")
    else:
        with st.spinner("Gemini is analyzing the image structure..."):
            try:
                # Use Gemini 2.5 Flash for its excellent vision capabilities
                vision_model = genai.GenerativeModel('gemini-2.5-flash')
                img = Image.open(uploaded_file)
                
                instruction = f"Act as an expert AI prompt engineer for Nano Banana. Look at the exact structure, composition, and layout of the attached image. {('Additional details: ' + extra_details) if extra_details else ''}. Write a highly detailed, comma-separated prompt to recreate this exact composition as a {target_style} masterpiece. Include lighting, camera angles, and high-quality textures. Only output the raw prompt text."
                
                response = vision_model.generate_content([instruction, img])
                
                # Save the prompt into session state so it is ready for Step 2
                st.session_state.generated_prompt = response.text.strip()
                st.success("Prompt successfully generated!")
            except Exception as e:
                st.error(f"Error generating prompt: {e}")

st.divider()

# ==========================================
# STEP 2: EDIT PROMPT & GENERATE IMAGE
# ==========================================
st.header("2️⃣ Edit Prompt & Generate Image")

# The text area value is tied directly to the session state we saved in Step 1
edited_prompt = st.text_area("Review and Edit Your Prompt:", value=st.session_state.generated_prompt, height=150)

# If the user types manually, update the session state with their new text
if edited_prompt != st.session_state.generated_prompt:
    st.session_state.generated_prompt = edited_prompt

if st.button("Generate Image 🍌", type="primary"):
    if not st.session_state.generated_prompt.strip():
        st.warning("Please generate or write a prompt first!")
    else:
        with st.spinner("Nano Banana is rendering your masterpiece..."):
            try:
                # Note: In the Google API, Nano Banana's backend is accessed via the "imagen-3.0-generate-001" model
                image_model = genai.ImageGenerationModel("imagen-3.0-generate-001")
                
                result = image_model.generate_images(
                    prompt=st.session_state.generated_prompt,
                    number_of_images=1,
                    aspect_ratio="1:1" # You can change this to 16:9 or 9:16 if you prefer
                )
                
                # Display the generated image
                # (We use a try/except because different versions of the SDK format the output slightly differently)
                try:
                    final_image = result.generated_images[0].image
                except AttributeError:
                    final_image = result.images[0] 
                
                st.image(final_image, caption="Generated by Nano Banana Studio", use_container_width=True)
                
            except Exception as e:
                st.error(f"Image generation failed. Error: {e}")
